"""Deterministic rule-based report (fallback when the LLM is not configured
or its call fails).

All threshold decisions are based on metrics computed by the engine; the
output is explicitly labeled as a rule-based report.

Multilingual (2026-08): `rule_based_report(ctx, lang)` renders the template
from `_TEXT[lang]` (zh-CN / en-US / ja-JP; unknown codes fall back to zh-CN).
Threshold logic is identical across languages — only the wording differs.
"""
from __future__ import annotations

_TEXT: dict[str, dict[str, str]] = {
    "zh-CN": {
        "rule_note": "> ⚠️ 规则报告（未接入 LLM）。由确定性规则从指标生成，仅覆盖常见模式；"
                     "接入 API key 后可获得完整 AI 分析。",
        "conclusion": "## 结论",
        "conclusion_body": "《{song}》[{diff}] 总分 {score}（重算 {recomputed}），"
                           "accuracy {acc}%，Good/Bad/Miss = {good}/{bad}/{miss}，{fc}。",
        "fc_yes": "Full Combo",
        "fc_no": "非 FC",
        "bottleneck": "## 主要瓶颈",
        "center_weak": "- **Center（切准）是首要瓶颈**：左手 {lc}/15，右手 {rc}/15，"
                       "而 Pre（{lp}/70、{rp}/70）与 Post（{lpost}/30、{rpost}/30）"
                       "相对更高——符合 H1/H2 假设的形态：挥刀框架完整、切准退化。",
        "asym": "- **左右手 Center 不对称**：差 {d} 分（{better}更好），"
                "建议弱手单独做低速切准练习。",
        "better_right": "右手",
        "better_left": "左手",
        "miss_density": "- **失误密度偏高**：Bad {bad} + Miss {miss}（{pct}%），"
                        "需要定位时间窗（见时间序列图）。",
        "reversal": "- **{hand}手高速连续段跟不上**：失误集中度 {conc}（高速段失误率"
                    "显著高于整体），高速段占比 {ratio}{ret_part}，与 H3 的单手换向"
                    "问题一致。",
        "ret_part": "，且高速段刀速仅为低速段的 {ret}",
        "hand_left": "左",
        "hand_right": "右",
        "no_finding": "- 未发现显著结构性瓶颈（规则阈值内）。",
        "evidence": "## 证据（关键指标）",
        "ev_pre_l": "- Pre/Center/Post 左: {lp} / {lc} / {lpost}",
        "ev_pre_r": "- Pre/Center/Post 右: {rp} / {rc} / {rpost}",
        "ev_cut": "- cut 距离均值 左 {l} cm / 右 {r} cm",
        "ev_speed": "- 刀速均值 左 {l} / 右 {r}",
        "fatigue": "## 后程变化（运动学推断，非医学诊断）",
        "fat_part_acc": "accuracy {v}",
        "fat_part_center": "Center {v}",
        "fat_part_miss": "miss 率 {v}",
        "fat_trend": "- 前段 vs 后段：{trend} → {verdict}。",
        "fat_verdict_bad": "后段出现与局部疲劳一致的运动学特征",
        "fat_verdict_ok": "后段未见系统性下降",
        "fat_short": "- 歌曲过短或窗口数据不足，无法对比。",
        "fat_empty": "- 无疲劳数据。",
        "history": "## 历史同谱对比",
        "hist_row": "- {ts}：score {score}，acc {acc}%，miss {miss}",
        "hist_best": "- 本次 accuracy 超过历史同谱最佳（{acc}%）。",
        "hist_none": "- 暂无同谱历史记录（这是该谱第一份本地分析）。",
        "advice": "## 下一轮建议",
        "advice1": "1. 单变量优先：若调整 Saber Offset，一次只动一个轴（如只调 X 位移），"
                   "同谱打 3-5 把再对比。",
        "advice2": "2. 若 Center 是瓶颈：选低密度谱面刻意练习切准（盯 cut_distance_cm 均值下降）。",
        "advice3": "3. 若高速段失误集中：降低 10-20% 速度练连续段，观察 "
                   "fast_fail_concentration 是否回落到 1 附近。",
        "uncertainty": "## 不确定性",
        "unc1": "- 本报告由固定规则生成，无法结合谱面结构与你的训练史做深层解释。",
        "unc2": "- 疲劳指标是运动学推断，可能受体温、状态、谱面结构影响。",
    },
    "en-US": {
        "rule_note": "> ⚠️ Rule-based report (no LLM connected). Generated by deterministic "
                     "rules from the metrics and only covers common patterns; connect an "
                     "API key for full AI analysis.",
        "conclusion": "## Conclusion",
        "conclusion_body": "“{song}” [{diff}] — total score {score} (recomputed {recomputed}), "
                           "accuracy {acc}%, Good/Bad/Miss = {good}/{bad}/{miss}, {fc}.",
        "fc_yes": "Full Combo",
        "fc_no": "No FC",
        "bottleneck": "## Main bottleneck",
        "center_weak": "- **Center (accuracy score) is the main bottleneck**: left hand "
                       "{lc}/15, right hand {rc}/15, while Pre ({lp}/70, {rp}/70) and "
                       "Post ({lpost}/30, {rpost}/30) are comparatively higher — matching "
                       "the H1/H2 hypothesis pattern: full swing framework, degraded "
                       "center accuracy.",
        "asym": "- **Left/right Center asymmetry**: {d}-point gap ({better} is better). "
                "Drill center accuracy with the weaker hand alone at low speed.",
        "better_right": "right hand",
        "better_left": "left hand",
        "miss_density": "- **High miss density**: Bad {bad} + Miss {miss} ({pct}%). "
                        "Locate the offending time windows (see the timeline chart).",
        "reversal": "- **{hand} hand falls behind in fast consecutive segments**: miss "
                    "concentration {conc} (miss rate in fast segments significantly above "
                    "the overall rate), fast-segment share {ratio}{ret_part} — consistent "
                    "with the H3 single-hand direction-change problem.",
        "ret_part": ", and fast-segment saber speed is only {ret} of the slow segments",
        "hand_left": "left",
        "hand_right": "right",
        "no_finding": "- No significant structural bottleneck found (within rule thresholds).",
        "evidence": "## Evidence (key metrics)",
        "ev_pre_l": "- Pre/Center/Post left: {lp} / {lc} / {lpost}",
        "ev_pre_r": "- Pre/Center/Post right: {rp} / {rc} / {rpost}",
        "ev_cut": "- Mean cut distance, left {l} cm / right {r} cm",
        "ev_speed": "- Mean saber speed, left {l} / right {r}",
        "fatigue": "## Late-game changes (kinematic proxy, not a medical diagnosis)",
        "fat_part_acc": "accuracy {v}",
        "fat_part_center": "Center {v}",
        "fat_part_miss": "miss rate {v}",
        "fat_trend": "- First half vs. second half: {trend} → {verdict}.",
        "fat_verdict_bad": "second half shows kinematic features consistent with local fatigue",
        "fat_verdict_ok": "no systematic decline in the second half",
        "fat_short": "- Song too short or insufficient window data to compare.",
        "fat_empty": "- No fatigue data.",
        "history": "## Same-map history",
        "hist_row": "- {ts}: score {score}, acc {acc}%, miss {miss}",
        "hist_best": "- This run's accuracy exceeds the previous same-map best ({acc}%).",
        "hist_none": "- No same-map history yet (this is the first local analysis of this map).",
        "advice": "## Next round suggestions",
        "advice1": "1. Change one variable at a time: if you adjust Saber Offset, move only "
                   "one axis (e.g. only the X offset), then play the same map 3–5 times "
                   "before comparing.",
        "advice2": "2. If Center is the bottleneck: pick a low-density map and deliberately "
                   "drill center accuracy (watch the mean cut_distance_cm drop).",
        "advice3": "3. If misses cluster in fast segments: lower the speed by 10–20% and "
                   "practice the consecutive segments, checking whether "
                   "fast_fail_concentration returns to around 1.",
        "uncertainty": "## Uncertainty",
        "unc1": "- This report is generated by fixed rules and cannot combine map structure "
                "with your training history for deeper interpretation.",
        "unc2": "- Fatigue metrics are kinematic proxies and may be affected by body "
                "temperature, form, and map structure.",
    },
    "ja-JP": {
        "rule_note": "> ⚠️ ルールベースレポート（LLM 未接続）。指標から決定性ルールで生成され、"
                     "一般的なパターンのみを対象としています。API key を接続すると、"
                     "完全な AI 分析が利用できます。",
        "conclusion": "## 結論",
        "conclusion_body": "《{song}》[{diff}] 総合得点 {score}（再計算 {recomputed}）、"
                           "accuracy {acc}%、Good/Bad/Miss = {good}/{bad}/{miss}、{fc}。",
        "fc_yes": "Full Combo",
        "fc_no": "FC なし",
        "bottleneck": "## 主要ボトルネック",
        "center_weak": "- **Center（切れ味）が主要ボトルネック**：左手 {lc}/15、右手 {rc}/15、"
                       "一方 Pre（{lp}/70、{rp}/70）と Post（{lpost}/30、{rpost}/30）は"
                       "比較的高い——H1/H2 仮説のパターンと一致：スイングのフレームは"
                       "しっかりしているが、切れ味のみが低下している。",
        "asym": "- **左右の Center が非対称**：差 {d} 点（{better}のほうが高い）。"
                "弱い手だけで低速の切れ味練習をするのがおすすめです。",
        "better_right": "右手",
        "better_left": "左手",
        "miss_density": "- **ミス密度が高い**：Bad {bad} + Miss {miss}（{pct}%）。"
                        "該当するタイムウィンドウを特定しましょう（タイムライン図参照）。",
        "reversal": "- **{hand}手が高速連続セクションについていけない**：ミス集中度 {conc}"
                    "（高速区間のミス率が全体より顕著に高い）、高速区間の割合 {ratio}{ret_part}"
                    "——H3 の片手切り返し問題と一致。",
        "ret_part": "、かつ高速区間の刀速は低速区間の {ret} のみ",
        "hand_left": "左",
        "hand_right": "右",
        "no_finding": "- 顕著な構造的ボトルネックは見つからなかった（ルール閾値内）。",
        "evidence": "## 根拠（主要指標）",
        "ev_pre_l": "- Pre/Center/Post 左: {lp} / {lc} / {lpost}",
        "ev_pre_r": "- Pre/Center/Post 右: {rp} / {rc} / {rpost}",
        "ev_cut": "- cut 距離の平均 左 {l} cm / 右 {r} cm",
        "ev_speed": "- 刀速の平均 左 {l} / 右 {r}",
        "fatigue": "## 後半の変化（運動学的推測であり、医学的診断ではない）",
        "fat_part_acc": "accuracy {v}",
        "fat_part_center": "Center {v}",
        "fat_part_miss": "ミス率 {v}",
        "fat_trend": "- 前半 vs 後半：{trend} → {verdict}。",
        "fat_verdict_bad": "後半に、局所的疲労と一致する運動学的特徴が見られる",
        "fat_verdict_ok": "後半に系統的な低下は見られない",
        "fat_short": "- 曲が短すぎるか、ウィンドウのデータが不足しているため比較できません。",
        "fat_empty": "- 疲労データなし。",
        "history": "## 同譜面の過去比較",
        "hist_row": "- {ts}：score {score}、acc {acc}%、miss {miss}",
        "hist_best": "- 今回の accuracy が同譜面の過去最高（{acc}%）を上回りました。",
        "hist_none": "- 同譜面の過去記録はありません（この譜面の最初のローカル分析です）。",
        "advice": "## 次回の提案",
        "advice1": "1. 単変数優先：Saber Offset を調整する場合、一度に一軸のみ変更"
                   "（例：X 変位のみ）、同譜面で 3-5 回プレイして比較。",
        "advice2": "2. Center がボトルネックの場合：低密度譜面で切れ味の練習"
                   "（cut_distance_cm 平均の低下を確認）。",
        "advice3": "3. 高速区間のミス集中：速度を 10-20% 落として連続セクションの練習、"
                   "fast_fail_concentration が 1 付近に戻るか確認。",
        "uncertainty": "## 不確実性",
        "unc1": "- 本レポートは固定ルールで生成され、譜面構造や練習履歴を考慮した"
                "深い解釈はできません。",
        "unc2": "- 疲労指標は運動学的推測であり、体温・体調・譜面構造の影響を受けます。",
    },
}


def _v(d: dict, *keys, default=None):
    cur = d
    for k in keys:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(k)
        if cur is None:
            return default
    if isinstance(cur, dict):
        return cur.get("value", default)
    return cur


def rule_based_report(ctx: dict, lang: str = "zh-CN") -> str:
    T = _TEXT.get(lang) or _TEXT["zh-CN"]
    r = ctx.get("replay", {})
    left = ctx.get("hands", {}).get("left", {})
    right = ctx.get("hands", {}).get("right", {})
    fat = ctx.get("fatigue", {})
    hist = ctx.get("history_same_map", [])

    lines = [
        T["rule_note"],
        "",
        T["conclusion"],
        T["conclusion_body"].format(
            song=r.get("song_name"), diff=r.get("difficulty"),
            score=r.get("score"), recomputed=r.get("score_recomputed"),
            acc=float(r.get("accuracy") or 0) * 100,
            good=r.get("good"), bad=r.get("bad"), miss=r.get("miss"),
            fc=T["fc_yes"] if r.get("full_combo") else T["fc_no"],
        ),
        "",
        T["bottleneck"],
    ]

    findings = []
    lc = _v(left, "center_score_avg", default=0) or 0
    rc = _v(right, "center_score_avg", default=0) or 0
    lp = _v(left, "pre_score_avg", default=0) or 0
    rp = _v(right, "pre_score_avg", default=0) or 0
    lpost = _v(left, "post_score_avg", default=0) or 0
    rpost = _v(right, "post_score_avg", default=0) or 0

    center_weak = min(lc, rc) < 8.0
    if center_weak:
        findings.append(T["center_weak"].format(
            lc=lc, rc=rc, lp=lp, rp=rp, lpost=lpost, rpost=rpost))
    asym_c = abs(lc - rc)
    if asym_c > 0.8:
        better = T["better_right"] if rc > lc else T["better_left"]
        findings.append(T["asym"].format(d=asym_c, better=better))
    miss = r.get("miss") or 0
    bad = r.get("bad") or 0
    total_notes = (r.get("good") or 0) + miss + bad
    if total_notes and (miss + bad) / max(1, total_notes) > 0.03:
        findings.append(T["miss_density"].format(
            bad=bad, miss=miss, pct=(miss + bad) / total_notes * 100))

    # Fast consecutive cutting (§12)
    for hand in ("left", "right"):
        h = ctx.get("hands", {}).get(hand, {})
        conc = _v(h, "fast_fail_concentration", default=None)
        fast_ratio = _v(h, "fast_ratio", default=None)
        ret = _v(h, "speed_retention", default=None)
        if conc is not None and fast_ratio is not None and conc > 1.5 and fast_ratio > 0.05:
            hand_name = T["hand_left"] if hand == "left" else T["hand_right"]
            ret_part = ""
            if ret is not None and ret < 0.9:
                ret_part = T["ret_part"].format(ret=ret)
            findings.append(T["reversal"].format(
                hand=hand_name, conc=conc, ratio=fast_ratio, ret_part=ret_part))
    if not findings:
        findings.append(T["no_finding"])
    lines.extend(findings)

    lines += ["", T["evidence"],
              T["ev_pre_l"].format(lp=lp, lc=lc, lpost=lpost),
              T["ev_pre_r"].format(rp=rp, rc=rc, rpost=rpost),
              T["ev_cut"].format(l=_v(left, 'cut_distance_cm_avg', default=0),
                                 r=_v(right, 'cut_distance_cm_avg', default=0)),
              T["ev_speed"].format(l=_v(left, 'saber_speed_avg', default=0),
                                   r=_v(right, 'saber_speed_avg', default=0)),
              ]

    # Fatigue
    lines += ["", T["fatigue"]]
    if fat:
        d_acc = fat.get("delta_accuracy")
        d_center = fat.get("delta_center")
        d_miss = fat.get("delta_miss_rate")
        parts = []
        if d_acc is not None:
            parts.append(T["fat_part_acc"].format(v=f"{d_acc:+.3f}"))
        if d_center is not None:
            parts.append(T["fat_part_center"].format(v=f"{d_center:+.2f}"))
        if d_miss is not None:
            parts.append(T["fat_part_miss"].format(v=f"{d_miss:+.3f}"))
        if parts:
            trend = ", ".join(parts)
            verdict = T["fat_verdict_bad"] if (
                (d_center is not None and d_center < -0.5) or
                (d_miss is not None and d_miss > 0.01)) else T["fat_verdict_ok"]
            lines.append(T["fat_trend"].format(trend=trend, verdict=verdict))
        else:
            lines.append(T["fat_short"])
    else:
        lines.append(T["fat_empty"])

    # History
    lines += ["", T["history"]]
    if hist:
        for h in hist[:3]:
            lines.append(T["hist_row"].format(
                ts=h.get("timestamp"), score=h.get("score"),
                acc=float(h.get("accuracy") or 0) * 100,
                miss=h.get("miss_count")))
        cur_acc = float(r.get("accuracy") or 0)
        prev_best = max((float(h.get("accuracy") or 0) for h in hist), default=0)
        if cur_acc > prev_best + 0.001:
            lines.append(T["hist_best"].format(acc=prev_best * 100))
    else:
        lines.append(T["hist_none"])

    lines += [
        "",
        T["advice"],
        T["advice1"],
        T["advice2"],
        T["advice3"],
        "",
        T["uncertainty"],
        T["unc1"],
        T["unc2"],
    ]
    return "\n".join(lines)
